import pandas as pd
df = pd.read_csv("data/Sales.csv")
print("==== DATA SHAPE====")
print(df.shape)
print("====MISSING VALUES====")
print(df.isnull().sum())
print("====LAST 5 ROWS====")
print(df.tail())
print("====DUPLICATES ROWS====")
print(df.duplicated().sum())
print("====STATISTICS====")
print(df.describe())
print("====TOTAL SALES====")
print(df["TotalPrice"].sum())
print("====AVERAGE SALES====")
print(df["TotalPrice"].mean())
print("====MAXIMUM SALE====")
print(df["TotalPrice"].max())
print("====MINIMUM SALE====")
print(df["TotalPrice"].min())